version: '2.1'

volumes:
  nginx-data:
  nginx-logs:
  MQTT-data:
  MQTT-log:
  nodered-data:
  nodered-log:
  dsmrdb-localtime:
  dsmrdb-data:
  dsmr-backup:

services:
  nginx:
    build: ./nginx
    privileged: true
    network_mode: host
    restart: 'unless-stopped'
    volumes:
      - nginx-data:/etc/letsencrypt
      - nginx-logs:/logs
    ports:
      - "80:80"
      - "443:443"
#MQTT
  MQTT:
    build: MQTT
    volumes:
      - 'MQTT-data:/mosquitto/data'
      - 'MQTT-log:/mosquitto/log'
      - 'nginx-data:/etc/letsencrypt'
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped

#Nodered
  nodered:
    build: nodered
    volumes:
      - 'nodered-data:/data'
    devices:
      - /dev/ttyUSB0:/dev/P1
    privileged: true
    ports:
      - "1880:1880"
    depends_on:
      - MQTT
    restart: unless-stopped

#mariaDB
  MariaDB:
    build: MariaDB

  dsmrdb:
    image: postgres:10.5-alpine
    container_name: dsmrdb
    restart: always
    volumes:
      - 'dsmrdb-localtime:/etc/localtime:ro'
      - 'dsmrdb-data:/var/lib/postgresql/data'
    environment:
      - TZ=Europe/Amsterdam
      - PG_TZ=Europe/Amsterdam
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader

  dsmr:
#    build: .
    image: xirixiz/dsmr-reader-docker:test-latest
    container_name: dsmr
    depends_on:
      - dsmrdb
    cap_add:
      - NET_ADMIN
    links:
      - dsmrdb
    restart: always
    volumes:
      - dsrmdb-localtime:/etc/localtime:ro
      - dsmr-backup:/dsmr/backups
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=localhost
      - SD_AUTOSTART_MQTT=false
      - SD_AUTORESTART_MQTT=false
    ports:
      - 7777:80
      - 7779:443
    devices:
      - /dev/ttyUSB0:/dev/
