version: '2.1'

volumes:
  nginx-data:
  nginx-logs:
  MQTT-data:
  MQTT-log:
  nodered-data:
  nodered-log:
  sense-data:

services:
  nginx:
    build: ./nginx
    privileged: true
    network_mode: host
    restart: 'unless-stopped'
    volumes:
      - nginx-data:/etc/letsencrypt
      - nginx-logs:/logs
    ports:
      - "80:80"
      - "443:443"
#MQTT
  MQTT:
    build: MQTT
    volumes:
      - 'MQTT-data:/mosquitto/data'
      - 'MQTT-log:/mosquitto/log'
      - 'nginx-data:/etc/letsencrypt'
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped

#Nodered
  nodered:
    build: nodered
    volumes:
      - 'nodered-data:/data'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
#    group-add:
#      - 'dialout'
    environment:
      - UDEV=1
#    privileged: true
    ports:
      - "1880:1880"
    depends_on:
      - MQTT
    restart: unless-stopped
#influxdb
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
#grafana
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "8080"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'HOME_DASHBOARD_UID=balenaSense'
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=8080'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
#telegraf
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
