version: '2.1'

volumes:
  nginx-data:
  nginx-logs:
  MQTT-data:
  MQTT-log:
  nodered-data:
  nodered-log:
<<<<<<< HEAD
  PHPMyadmin-data:
  PHPMyadmin-log:

=======
>>>>>>> 43cff31d410f5538687c374b15643f3edec0fcbe

services:
  nginx:
    build: ./nginx
    privileged: true
    network_mode: host
    restart: 'unless-stopped'
    volumes:
      - nginx-data:/etc/letsencrypt
      - nginx-logs:/logs
    ports:
      - "80:80"
      - "443:443"
#MQTT
  MQTT:
    build: MQTT
    volumes:
      - 'MQTT-data:/mosquitto/data'
      - 'MQTT-log:/mosquitto/log'
      - 'nginx-data:/etc/letsencrypt'
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped

#Nodered
  nodered:
    build: nodered
    volumes:
<<<<<<< HEAD
      - 'nodered-data:/data'
=======
<<<<<<< HEAD
      - 'nodered-data:/data'
=======
      - 'nodered-data:/mnt/data'
>>>>>>> 8cb13602656c5579b2f980ba050ba3ca467b2a20
>>>>>>> 43cff31d410f5538687c374b15643f3edec0fcbe
    ports:
      - "1880:1880"
    depends_on:
      - MQTT
    restart: unless-stopped
<<<<<<< HEAD

#MPHPMyadmin
  PHPMyadmin:
    build: PHPMyadmin

#mariaDB
  MariaDB:
    build: MariaDB
=======
#  ddclient:
#    build: ./ddclient
#    restart: 'always'
#  netdata:
#    build: ./netdata
#    pid: "host"
#    ports:
#      - 19999:19999
#    network_mode: host
#    cap_add:
#      - SYS_PTRACE
#    security_opt:
#      - apparmor:unconfined
#    privileged: true
#    labels:
#      io.balena.features.sysfs: '1'
#      io.balena.features.procfs	: '1'
#      io.balena.features.balena-socket: '1'
#      io.resin.features.kernel-modules: '1'
#      io.resin.features.firmware: '1'
#    environment:
#      - DOCKER_USR=root
#      - VIRTUALIZATION=${VIRTUALIZATION}
#    depends_on:
#      - nginx
>>>>>>> 43cff31d410f5538687c374b15643f3edec0fcbe
