version: '2.1'

volumes:
  nginx-data:
  nginx-logs:
  MQTT-data:
  MQTT-log:
  nodered-data:
  nodered-log:
  influxdb-data:
  grafana-data:
  grafana-logs:
  grafana-users:

services:
  nginx:
    build: ./nginx
    privileged: true
    network_mode: host
    restart: 'unless-stopped'
    volumes:
      - nginx-data:/etc/letsencrypt
      - nginx-logs:/logs
    ports:
      - "80:80"
      - "443:443"
#MQTT
  MQTT:
    build: MQTT
    volumes:
      - 'MQTT-data:/mosquitto/data'
      - 'MQTT-log:/mosquitto/log'
      - 'nginx-data:/etc/letsencrypt'
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped

#Nodered
  nodered:
    build: nodered
    volumes:
      - 'nodered-data:/data'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
#    group-add:
#      - 'dialout'
    environment:
      - UDEV=1
    privileged: true
    ports:
      - "1880:1880"
    depends_on:
      - MQTT
    restart: unless-stopped

  influxdb:
    build: influxdb
    container_name: influxdb
    # privileged added so usb drive can be mounted.
    privileged: true
    volumes:
        # take care that the mount location "/mnt/influxdb" becomes overwritten
        # by the mount location specified in the influxdb Dockerfile.
        - 'influxdb-data:/mnt/influxdb'
    ports:
      # The API for InfluxDB is served on port 8086
      - "8082:8082"
      - "8086:8086"
      # UDP Port
      - "8089:8089"
    restart: unless-stopped
  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    build : telegraf
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    depends_on:
      - influxdb
    restart: unless-stopped
    environment:
       - interval=60s
       - flush_interval=60s
  grafana:
    build: grafana
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: unless-stopped
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - 'grafana-users:/usr/share/grafana'
      - 'grafana-logs:/var/log/grafana'
