version: '2.1'

volumes:
  nginx-data:
  nginx-logs:
  MQTT-data:
  MQTT-log:
  nodered-data:
  nodered-log:

services:
  nginx:
    build: ./nginx
    privileged: true
    network_mode: host
    restart: 'unless-stopped'
    volumes:
      - nginx-data:/etc/letsencrypt
      - nginx-logs:/logs
    ports:
      - "80:80"
      - "443:443"
#MQTT
  MQTT:
    build: MQTT
    volumes:
      - 'MQTT-data:/mosquitto/data'
      - 'MQTT-log:/mosquitto/log'
      - 'nginx-data:/etc/letsencrypt'
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: unless-stopped

#Nodered
  nodered:
    build: nodered
    volumes:
      - 'nodered-data:/data'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
#    group-add:
#      - 'dialout'
    environment:
      - UDEV=1
#    privileged: true
    ports:
      - "1880:1880"
    depends_on:
      - MQTT
    restart: unless-stopped
